### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by Sky1414** [MrPig91/PSChiaPlotter#100]
Error with Refresh
![image](https://user-images.githubusercontent.com/83701847/121891953-6c9dee80-cd1c-11eb-9d25-8957b5b762ec.png)

**Comment by MrPig91** [comment]
That is interesting. I will look into it when I have some more free time. I glanced over the code and I did not identify anywhere that would prompt that error since all the objects it processes have the property FreeSpace. Unless... now that I think about it. One drive shows up twice when it is trying to match drives then it would create an array which would not have that property.

**Comment by MrPig91** [comment]
Have not come across this issue since, please re-open if this is still an issue.
