### ISSUE TITLE
Question, not a bug

### ISSUE THREAD

**Issue by OhNOherewegoagain** [MrPig91/PSChiaPlotter#101]
Hello, i just dont know where to ask this question. Thanks to the plots counter i found a problem. My ryzen 5600x is plotting 22 plots a day, with 3 temp NVMe drives, but my ryzen 5950x with 16 cores is plotting 20 plots a day with 4 same NVMe drives, i found that the first plots complete in 4 hours. and as the queue builds up it gets up to 15 hours, mainly the phases 1 and 3 take up to 5-6 hours.
The settings are 
12 plots in parallel. 4000ram, 6 threads

**Comment by MrPig91** [comment]
That is a pretty big range of plot completion time if it is between 4-15 hours. You said the biggest difference is in phases 1 and 3, did you notice the copy phase taking a longer time too or does that stay about the same? What is your stagger time (if any). One recommendation I would give is to lower the threads to 4, since I have read that anything past has diminishing returns.
