### ISSUE TITLE
[question] Plotting portable plots

### ISSUE THREAD

**Issue by ClementN** [MrPig91/PSChiaPlotter#141]
Hello,

For plotting the new portable plots is it enough to fill (and check) the "Pool Contract Address" field? 

Is it ok to leave empty the "Farmer Public Key" and "Pool Public Key" even if we want to plot without having the keys on that machine?

**Comment by MrPig91** [comment]
Hey @ClementN ,
I personally have not tried pool plotting yet, so perhaps someone can correct me if I am wrong, but you will still want to put in your Farmer Public Key when creating portable plots. The Pool Public Key parameter cannot be used when using the Pool Contract parameter which is why I have that field disabled when you check the pool contract checkbox. Again, I have not made any portable plots myself so I wouldn't go off just my word.

**Comment by ClementN** [comment]
I confirm your answer is confirmed by tests.

Thank you very much
