### ISSUE TITLE
Phase 3/4 buckets size not working

### ISSUE THREAD

**Issue by Scoobs72** [MrPig91/PSChiaPlotter#146]
In 1.0.51 it seems that the option to state a different phase 3/4 bucket size is not working.  Running a plot using Mad max, the logs show the Phase 3/4 bucket size to be the same as the phase 1/2 bucket size, even when phase 3/4 is set to a different value, e.g. 512 for phase 1/2 and 128 for phase 3/4 results in 512 for all phases.

**Comment by Sekaiji** [comment]
I have the same issue :
Number of Buckets P1:    2^9 (512)
Number of Buckets P3+P4: 2^9 (512)

**Comment by MrPig91** [comment]
I think I know the problem. I had it only use that option if the default value was changed from 128. If the the value wasn’t it changed it didn’t use that parameter. I did this so that older versions of madmax could still work, but now I realize the flaw. I will make the label for that parameter a check box to enable it instead.

**Comment by MrPig91** [comment]
Finally back from vacation and will get this fixed tomorrow after work, thank you for your patience.

**Comment by MrPig91** [comment]
This has now been fixed. You will have to check the checkbox for that field to enable this parameter but it should work as expected once checked.
