### ISSUE TITLE
Runs starting simultaneous with MM - is this ok?

### ISSUE THREAD

**Issue by ClementN** [MrPig91/PSChiaPlotter#177]
Hello,

On different machines, sometimes 2 runs starts in the same moment despite the queue delay being set to 60 mins.

This is not happening when PSCP starts it first round of runs but later in time after the parallel plotting was running for a while. 

Is there an explanation for that?

Thank you,

**Comment by MrPig91** [comment]
Just for a little more context, you have a MM job that has parallel plotting with a delay time set to 60 minutes? Or are you using the First delay? How many parallel plots do you have set? Sorry I just need a little more context.

**Comment by ClementN** [comment]
Thank you for the reply!

I have 4 machines. 

All of them have MM jobs. 

2 machines:
1 job - 4 parallel runs - delay time 60 minutes - First delay 0 

1 machine:
2 jobs - 4 parallel runs each ( 8 parallel in total) - delay time 60 minutes - First delay 45 minute for the second job

1 machine:
2 jobs - 6 parallel runs each ( 12 parallel in total) - delay time 60 minutes - First delay 45 minute for the second job


On all machines, some consecutive runs have exactly same Percentage and Run Time (sometime exact time, some times with 1 minute difference).

Mostly there are 2 of them but I saw cases with 3 similar runs. 

![20210716_175845](https://user-images.githubusercontent.com/293105/125968069-46abcfa8-fc1c-4fa1-bb13-3c1938cbc784.jpg)

**Comment by MrPig91** [comment]
Thank you for the detailed information. So I think this is normal behavior since the delay time is used in the beginning to stagger the queues, but with enough queues it is possible for the first queue to finish as a later queue is just starting. If you do want to ensure the queues are always staggered and not starting at the same time you might add limit phase 1 option with a limit of 1 and maybe set the delay to 0. This will stagger the starting of plots by phase 1 and will prevent them from starting at the same time. However having 2 jobs the phase 1 limit will only apply to the runs associated with that job.

**Comment by ClementN** [comment]
Everything looks fine for me so far. 

I don't see any problem with that. Just wanted tot make sure is normal behavior. 

Thank you very much for your time.

**Comment by MrPig91** [comment]
Thank you for double checking to ensure PSCP is working properly.
