### ISSUE TITLE
Suggestion: Add more convenient path parameter to Get-ChiaHarvesterActivity and Start-ChiaHarvesterWatcher

### ISSUE THREAD

**Issue by Deutschi** [MrPig91/PSChiaPlotter#43]
In the above mentioned scripts there is this parameter with a hardcoded path
`[string[]]$DebugLogFilePath = (Get-ChildItem -Path "$ENV:USERPROFILE\.chia\mainnet\log" -filter "debug.log*").FullName`

I have a special setup where my Chia logs are not in the standard folder. So I need to call the scripts like
`Get-ChiaHarvesterActivity -DebugLogFilePath (Get-ChildItem -Path "\\network\chia\log" -filter "debug.log*").FullName -Summary`

However, it would be more convenient to use something like
`Get-ChiaHarvesterActivity -DebugLogFilePath "\\network\chia\log" -Summary`

Love the whole tool though, great work!

**Comment by MrPig91** [comment]
I wanted people to be able to chose only one log file if they wanted to, which is why I made the Path variable directed at file path rather than a directory path. I think changing it accept a directory path would limit the functions versatility. In theory I could have it check whether a directory or a file path was provided to the parameter, but I don't want to over-complicate things or make what the parameter accepts ambiguous. Thank you for the suggestion.
