### ISSUE TITLE
Idea: Ideentifying bottlekneck

### ISSUE THREAD

**Issue by AK1244** [MrPig91/PSChiaPlotter#72]
You could have a "test plot" that would do a normal plot and time all sorts of metrics (how long each phase takes (average time per bucket in each phase etc) and use that along with what was pegged at 100% which would identify what is slowing you down when plotting. It could also give you common things to make plotting faster (ie trimming your drive). I have 0 experience with code and would not know how to write this but just throwing ideas out there.

**Comment by Jacek-ghub** [comment]
I think that the problem is more complicated than that.  For instance, how would you detect that your CPU is power limited, or that your RAID0 for whatever reason is less optimal than running separate disks alone, etc.

Also, even though it is kind of related to this project, it is not really the goal of this project.  So far, this is the best plot management piece, and let's keep it like that - stay focused.

Still, one thing that I think would not hurt is to have the Plotter show in the summary box (lower left corner) how many final copy collisions happened.  I think that this is maybe one of the most underrated problem that potentially affects all high performance setups (I mean 10+ physical cores).

Although, I really like the idea, and think that having a (pinned?) thread dedicated to issues/improvements may work better where everyone could chime in, and the thread owner would be updating the main post may work better.

Thank you, Jacek

**Comment by MrPig91** [comment]
Some other tools in the PSChiaPlotter can help identify bottlenecks, I wanted to implement them into the GUI more but have not been able to do so due to time restraints.
