### ISSUE TITLE
Secondary Temporary Directory

### ISSUE THREAD

**Issue by broken-gage** [MrPig91/PSChiaPlotter#91]
Hi,

First of all, thanks for your hard work! It's awesome.

I found out that almost all third party plotter missing the function of secondary temp directory. I know most people rarely use it but it works great on my particular setup (I have two machine running with 2nd temp, and it smooths out the stress on the NVME). So I'm wondering if it is possible to add that option to the GUI?

Thanks again.

**Comment by MrPig91** [comment]
This is the next feature I am working on adding. I have actually already added it, but have not merged the branch yet because I need to do some testing. I am also adding changing KSizes, Saving jobs, basic directory input option in this update as well. You can check out the branch here - https://github.com/MrPig91/PSChiaPlotter/tree/Add2ndTempDrive

**Comment by MrPig91** [comment]
This has now been added. A lot was added to the latest update so please report any issues with it. The feature requested is in version 1.0.32 and above.
